### ISSUE TITLE
Code markdown doesn't respect language tag

### ISSUE THREAD

**Issue by Lukazoid** [MyNihongo/MudBlazor.Markdown#102]
Markdown for code blocks with a language specified such as ```csharp doesn't highlight the code for the specified language, instead it is using the highlight.js language detection logic.

I believe this is due to the use of `highlightElement`: https://github.com/MyNihongo/MudBlazor.Markdown/blob/4363af22b338b076b3a22180ad0e1da17949a8e7/src/MudBlazor.Markdown/Resources/MudBlazor.Markdown.js#L7 

Which from the highlight.js docs doesn't take any options, instead the language should be specified in the class attribute of the DOM node (see https://highlightjs.readthedocs.io/en/latest/api.html#highlightelement)

**Comment by MihailsKuzmins** [comment]
I have pushed a new [NuGet verison](https://www.nuget.org/packages/MudBlazor.Markdown/0.0.11). Could you please check whether or not it works as expected?
