### ISSUE TITLE
Rendering Math Expressions

### ISSUE THREAD

**Issue by Matthias-Hess** [MyNihongo/MudBlazor.Markdown#105]
I would like to include Math expressions like so:

When  $a \ne 0$ , there are two solutions to $(ax^2 + bx + c = 0)$ and they are 

$$ x = {-b \pm \sqrt{b^2-4ac} \over 2a} $$

this is supported in github markdown.

Can I make it work in MudMarkdown?

**Comment by Matthias-Hess** [comment]
Thank you for doing this hard work!

I can imagine that this is very hard to solve, because in Mathematics the Layouts can get very tricky.
I would be overwhelmed by the complexity of this, because there are so many things for this to work 100% correctly.

For example, matrices, integrals, OMG, so much work!

So... take your time

Thanks again

Matthias Hess



Von: MihailsKuzmins ***@***.***>
Gesendet: Mittwoch, 17. August 2022 10:46
An: MyNihongo/MudBlazor.Markdown ***@***.***>
Cc: Hess Matthias ***@***.***>; Author ***@***.***>
Betreff: Re: [MyNihongo/MudBlazor.Markdown] Rendering Math Expressions (Issue #105)


sorry, it takes longer than expected.
I do not really like to include mathjax directly since i don't really like their concept of changing the web page rather than rendering it straight away.
Hopefully it won't take forever...

-

**Comment by MihailsKuzmins** [comment]
I just had an idea.
Since it takes some time, could you please share what math operations are crucial for you. I think I will try to release them together with the `<details>` feature. Afterwards I will continue to improve rendering of math expressions
I hope that I need some easy expressions like $(ax^2 + bx + c = 0)$ since this is already dome :)

**Comment by Matthias-Hess** [comment]
Yes, at the moment it would be sufficient to have something lik $(ax^2 + bx + c = 0)$, because my Math examples are only for 12-14 years old students 😊.
So this would already be „good enough“ form e and offer a grat value.

Best Regards
Matthias

Von: MihailsKuzmins ***@***.***>
Gesendet: Freitag, 19. August 2022 15:44
An: MyNihongo/MudBlazor.Markdown ***@***.***>
Cc: Hess Matthias ***@***.***>; Author ***@***.***>
Betreff: Re: [MyNihongo/MudBlazor.Markdown] Rendering Math Expressions (Issue #105)


I just had an idea.
Since it takes some time, could you please share what math operations are crucial for you. I think I will try to release them together with the <details> feature. Afterwards I will continue to improve rendering of math expressions
I hope that I need some easy expressions like $(ax^2 + bx + c = 0)$ since this is already dome :)

**Comment by Matthias-Hess** [comment]
These are my top priority features


  1.  Fractions like       x = \frac{ 1 }{2}
  2.  Exponents like    ax^2
  3.  Roots like \sqrt {2}

Best Regards Matthias

Von: MihailsKuzmins ***@***.***>
Gesendet: Freitag, 19. August 2022 15:44
An: MyNihongo/MudBlazor.Markdown ***@***.***>
Cc: Hess Matthias ***@***.***>; Author ***@***.***>
Betreff: Re: [MyNihongo/MudBlazor.Markdown] Rendering Math Expressions (Issue #105)


I just had an idea.
Since it takes some time, could you please share what math operations are crucial for you. I think I will try to release them together with the <details> feature. Afterwards I will continue to improve rendering of math expressions
I hope that I need some easy expressions like $(ax^2 + bx + c = 0)$ since this is already dome :)

-

**Comment by MihailsKuzmins** [comment]
This input
![image](https://user-images.githubusercontent.com/47413092/187064452-5a9604fe-2003-4fab-9e21-bd37b48dd841.png)

will produce the following output
![image](https://user-images.githubusercontent.com/47413092/187064437-f7e3b436-1fa3-4e47-81da-d11f5e9d40a1.png)

I hope this works for you. I think I will close this issue, but if you encounter some problems, please reopen it or create a new one

**Comment by Matthias-Hess** [comment]
Thank you, this looks great

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
