### ISSUE TITLE
Nuget package includes package.json and package-lock.json files

### ISSUE THREAD

**Issue by erri120** [MyNihongo/MudBlazor.Markdown#11]
As the title suggests the nuget package contains these files as seen in the nusepc file:
```xml
    <contentFiles>
      <files include="any/net5.0/package-lock.json" buildAction="Content" />
      <files include="any/net5.0/package.json" buildAction="Content" />
    </contentFiles>
```

I think you have to explicitly set these files to not be packed into the nuget package similar to how you did it with the favico:

https://github.com/MyNihongo/MudBlazor.Markdown/blob/09d7c3a8127144eb8c3fcb91444f857fdd735e9b/src/MudBlazor.Markdown/MudBlazor.Markdown.csproj#L29-L34

**Comment by my-nihongo** [comment]
@erri120 thank you for issue. Indeed there is no need to pack `package.json` and `package-lock.json`
Now it should be fixed by #14.
