### ISSUE TITLE
tested issue #114, still problems

### ISSUE THREAD

**Issue by larseggan** [MyNihongo/MudBlazor.Markdown#117]
Hi,
I tested the latest version of MudBlazor.Markdown 0.0.12 regarding issue #114 and the `<details>` tag.
There are still problems if you have a crlf between the lines in the content that you use :
```
<details>
  <summary markdown="span">Release 1.0.1</summary>

**New**
-  Error fixes.

</details>
```

This works OK:
```
<details>
  <summary markdown="span">Release 1.0.1</summary>
**New**
-  Error fixes.
</details>
```

In Visual Studio I use the extension Markdown Editor v2 to validate the markdown, example 1 render OK, example 2 does not.

I did have a look in the code, but couldn’t figure out what to do.

**Comment by MihailsKuzmins** [comment]
That's because Markdig does not seem to parse this text correctly (as you can see below)
For now I advise you to use the markdown without spaces while this problem is investigated
![image](https://user-images.githubusercontent.com/47413092/187205799-7efd0a54-cadb-467c-9bf3-2a1b4b78524c.png)

**Comment by larseggan** [comment]
OK, that's the solution I found. Thanks for your help.
What's strange is that if I use markdig directly with Markdown.ToHtml and render it directly with cast to (MarkupString) the <details> is rendered correctly without MudMarkdown. But MudBlazor default uses incorrect font sizes for the rest.

**Comment by MihailsKuzmins** [comment]
I am not really sure what you are trying to accomplish, but the mandatory format is without spaces as it is stated [here](https://spec.commonmark.org/0.30/#html-blocks).
Otherwise, I don't think I can do anything with this issue and will probably need to close it without resolution
