### ISSUE TITLE
Style overrides

### ISSUE THREAD

**Issue by jstafford5380** [MyNihongo/MudBlazor.Markdown#128]
I noticed right away that tables were rendered with elevation and I can't really remove it. You may need to include additional delegates to override parameters on any mud components that you're using (e.g. tables) the same way you override typography styles. I'm not quite sure how it would look but maybe something where you take a delegate for the user to to implement, and you have your control pass in the instance of each table?

```xml
<MudMarkdown Value="@MyContent" OverrideTable="TransformTable" />

@code {
   MudTable TransformTable(MudTable tableInstance) {
    tableInstance.Elevation = 0; 
    return tableInstance;
   }
}
```

**Comment by MihailsKuzmins** [comment]
Now you can specify some styling like this
![image](https://user-images.githubusercontent.com/47413092/204472977-24107ea6-04ae-4e59-ae88-1556328ca85c.png)

It will produce the following output
![image](https://user-images.githubusercontent.com/47413092/204473116-8786d3d3-c6aa-434f-8470-636fbe42b611.png)
