### ISSUE TITLE
Copy code block to clipboard

### ISSUE THREAD

**Issue by MithrilMan** [MyNihongo/MudBlazor.Markdown#165]
Hi, thanks for the library!

Is it possible to have a "Copy to clipboard" button on code blocks?
Thanks

**Comment by MihailsKuzmins** [comment]
Now it should be done:
![copy](https://github.com/MyNihongo/MudBlazor.Markdown/assets/47413092/a64a0e38-ed15-41e0-aa0e-5d85d453e2e4)

**Comment by MithrilMan** [comment]
nice!, will it be released soon ?
