### ISSUE TITLE
After a cascading value changes, MudMarkDown is failing to update the corresponding value.

### ISSUE THREAD

**Issue by cristianalemanGit** [MyNihongo/MudBlazor.Markdown#166]
Hello, Is there a way to trigger a re-render of the MudMarkdown component when a cascading value is updated?

**Comment by MihailsKuzmins** [comment]
Could you please provide a code block (or a sample solution) of what you want to achieve and what does not work with the current version?

To force re-rendering you might try to call `StateHasChanged()` on your component when the cascading value is updated.

**Comment by cristianalemanGit** [comment]
I attempted to use StateHasChanged() but unfortunately, it did not refresh the MudMarkdown component. However, If 
the _htmlValue is placed on a MudText component, the value was successfully updated."

Here is a sample of my backEnd:
 ```
    [CascadingParameter]
    public Html Html { get; set; }

    private string _htmlValue;

    protected override void OnParametersSet()
    {
       
        _htmlValue = "```html\n" + Html + "\n```";
        
        StateHasChanged();
    }
```

And here is my frontEnd:
```
<MudCard>
    <MudCardHeader>
        <CardHeaderContent>
            <MudText Typo="Typo.body1">HTML Preview</MudText>
        </CardHeaderContent>
    </MudCardHeader>
    <MudCardContent>
        <MudMarkdown CodeBlockTheme="CodeBlockTheme.Default"
                     Value="@_htmlValue" />

        <MudText>@_htmlValue</MudText>
    </MudCardContent>
</MudCard>
```

**Comment by MihailsKuzmins** [comment]
Sorry for a late reply. Could you post a complete solutiuon with your expected behaviour? Otherwise I do not really understand what you are trying to accomplish.
Calling "StateHashChanged" does refresh the component

```razor
<MudButton OnClick="OnClick">Refresh</MudButton>

<MudMarkdown
	Value="@Value"
	Styling="Styling"
	TableCellMinWidth="100"
	OverrideLinkUrl="OverrideLink"
	OverrideHeaderTypo="OverrideHeaderTypo" 
	CodeBlockTheme="CodeBlockTheme.DraculaBase16" />

@code
{
	void OnClick()
	{
		Value += Environment.NewLine + Value;
		StateHasChanged();
	}

	protected override async Task OnInitializedAsync()
	{
		Value = "**aaa** bbb _aaa_";
	}
}
```
![refresh](https://github.com/MyNihongo/MudBlazor.Markdown/assets/47413092/09b848d7-4d55-411e-bd3d-ec0387a666b1)
