### ISSUE TITLE
Please let the padding-bottom be changed by the user

### ISSUE THREAD

**Issue by MattParkerDev** [MyNihongo/MudBlazor.Markdown#169]
Please let me do this with C# instead of overriding the stylesheet

![image](https://github.com/MyNihongo/MudBlazor.Markdown/assets/61717342/3809f119-0de6-465e-a23b-723f33cf7921)

**Comment by MattParkerDev** [comment]
Hi @MihailsKuzmins 
My bad, I realised the margin at the bottom of content I was experiencing was from the markdown content itself, not the MudMarkdown component. Thank you for your reply!

**Comment by simeyla** [comment]
@MihailsKuzmins I have blocks of markdown alongside other 'widgets' and I want to control the spacing with `<MudStack>`. So the extra spacing below a `<p>` is troublesome if it's the last paragraph.

This is my 'quick fix' - removes spacing from the final element. My markdown is mostly simple so I think this should work.

Added to App.razor.css:

```
::deep .mud-markdown-body :last-child {
    margin-bottom: 0 !important;
}
```
