### ISSUE TITLE
🐛 Margin-Bottom for Quote wrong

### ISSUE THREAD

**Issue by MattParkerDev** [MyNihongo/MudBlazor.Markdown#194]
The amount of margin-bottom for a quote is wrong:

![image](https://github.com/MyNihongo/MudBlazor.Markdown/assets/61717342/98ea7717-3e89-4e30-81c5-5455a8b5c521)

Should be:

![image](https://github.com/MyNihongo/MudBlazor.Markdown/assets/61717342/b7e38669-1816-4a20-8bc2-4e9dfde05bab)

PR to follow :)

**Comment by MattParkerDev** [comment]
Ive created a PR to fix :)

https://github.com/MyNihongo/MudBlazor.Markdown/pull/195

**Comment by MihailsKuzmins** [comment]
Thanks for finding the issue and submitting the PR. Please fix the code according to comments and submit the changes. Then I will make a new version.
