### ISSUE TITLE
Feature Request: Custom Pipeline

### ISSUE THREAD

**Issue by MaxGuernseyIII** [MyNihongo/MudBlazor.Markdown#197]
It would be nice to be able to set the pipeline as a parameter or inject the pipeline so I can use my own custom pipeline.

**Comment by MaxGuernseyIII** [comment]
I'd happily just write the PR but I couldn't find instructions on what the preferred way to contribute is. If you let me know what that is, I'll do it.

**Comment by MihailsKuzmins** [comment]
@MaxGuernseyIII  
I wonder what is the intention having your own custom pipeline? What conditions are there which are not satisfied by the current pipeline?

**Comment by MaxGuernseyIII** [comment]
To create an instance with features not supported out of the box.

**Comment by MihailsKuzmins** [comment]
> To create an instance with features not supported out of the box.

What instance are you talking about? And how is it related to the pipeline (CI/CD)?

Or do you mean that some markdown is not rendered correctly. If it is the case could you submit the markdown and I will take a look? Or you can just fork the repo, try to implement it yourself and submit a PR.

**Comment by MaxGuernseyIII** [comment]
I see the confusion, now. I mean a new markdown pipeline. Like there is
literally a field named _pipeline that I would like to have a Razor
parameter to set. Or, alternatively, I'd like to be able to inject it
through the service container. I'll give a more detail less description of
what I mean when I'm near a computer.

-- Max

There are 10 kinds of people: those who don't understand binary, those who
don't understand trinary, and so on...

**Comment by my-nihongo** [comment]
Hi, @MaxGuernseyIII 
Is this issue still relevant? If it is, could you please provide the requirements? Otherwise, I am afraid that I will be forced to close the issue assuming that it is irrelevant.

Sorry for causing trouble, but I ask for your cooperation.

**Comment by MaxGuernseyIII** [comment]
Yes. It's still relevant. Give me a few minutes.

**Comment by MaxGuernseyIII** [comment]
In MudMarkdown.razor.cs, line 13:

```CSharp
	private readonly MarkdownPipeline _pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();
```

Could be

```CSharp
        [Parameter]
	public MarkdownPipeline Pipeline { get; set; } = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();

        private MarkdownPipeline _pipeline => Pipeline;
```

That would make my life a lot easier.

**Comment by MaxGuernseyIII** [comment]
...or if you let me know what the preferred method for me to submit a PR is, I could just make the change, myself.

**Comment by MihailsKuzmins** [comment]
I see, so you want a custom `MarkdownPipeline` parameter. I would prefer supplying it as a parameter (`[Parameter]`), but in a slightly different way as you proposed. I think can try to look into it this weekend, does not sound like a lot of work.

**Comment by MaxGuernseyIII** [comment]
Thanks!

-- Max

There are 10 kinds of people: those who don't understand binary, those who
don't understand trinary, and so on...

**Comment by MihailsKuzmins** [comment]
@MaxGuernseyIII 
The `MarkdownPipeline` has been added. In the meantime you could download the code and check whether it is what you need. It will take some tome to take care of another issue you have created 🙇

**Comment by MaxGuernseyIII** [comment]
I'm so sorry. I never replied to this. Yes, it was what I wanted. My apologies for the year long delay in reply. I just now figured out how to find the global list of issues I've submitted.
