### ISSUE TITLE
Add BaseUrl option for relative links

### ISSUE THREAD

**Issue by erri120** [MyNihongo/MudBlazor.Markdown#21]
GitHub readmes often contain relative links which GitHub converts to absolute Urls. eg:
```markdown
![some image](assets/some_image.webp)
```

In the current version this will produce something like this:
```html
<img src="assets/some_image.webp" alt="some image"/>
```

I suggset adding some sort of `BaseUrl` option for the component which will be combined with the relative Url before creating the image component. I would define relative Urls as links that do not start with `#`, `https://`, `http://` or `www` but there might be other cases.

**Comment by my-nihongo** [comment]
So if I understand you correctly for
 ```gfm
![some image](assets/some_image.webp)
```
you want
```html
<img src="https://localhost/assets/some_image.webp" alt="some image"/>
```
right?

For example in this repository there is a relative link and GitHub does not convert it to the absolute link (GitHub applies its own magic). So if I understood your request correctly I would not rather do it because I think it more correct to leave it as the user specifies
sorry, GitHub made the image blurry
![image](https://user-images.githubusercontent.com/65362546/128896769-b52d591c-aedc-4669-94fe-7de726e693ef.png)

**Comment by erri120** [comment]
The readme of this repository links to the samples folder using the following markdown:
```markdown
For images how the markup component looks like in the browser go to the [README of samples](/samples)
```
which GitHub converst to an actual clickable link when you visit the repository page. The problem is that I mainly load readmes from GitHub which use relative links that point to some file in the repository. With some sort of `BaseUrl` option the Component would simply combine the links so `finalLink = BaseUrl + parsedLink`.

**Comment by my-nihongo** [comment]
So I understood your requirement right.
But still I don't see a use-case for it. Relative links are also ok.

Maybe if you provide a case where this requirement is necessary for you I will be able to understand

**Comment by erri120** [comment]
Let's take [this](https://raw.githubusercontent.com/jdsmith2816/emw/master/README.md) readme again:
```markdown
![emw-banner](extra/emw.png)
```
This works fine on GitHub because GitHub will get the image from `https://github.com/jdsmith2816/emw/blob/master/extra/emw.png` but the Markdown Component will simply use `extra/emw.png` which results in `https://localhost:5001/extra/emw.png` which does not exist:
![image](https://user-images.githubusercontent.com/16577545/128903958-22ab0f59-5ebf-4ab3-804a-fcc181756819.png)

**Comment by my-nihongo** [comment]
the behaviour is correct. The problem is that the image file is not located at your local repository
Adding a base URL which is not the actual base URL is a completely wrong approach which will mess up all the links.
E.g. your base URL is `https://localhost:5001/` then out of the blue you decide that your base URL is `https://www.google.co.jp/`. In this case all your relative links will go to Google

No, this is not shippable like this.

**Comment by erri120** [comment]
> 
> 
> the behaviour is correct. The problem is that the image file is not located at your local repository
> Adding a base URL which is not the actual base URL is a completely wrong approach which will mess up all the links.
> E.g. your base URL is `https://localhost:5001/` then out of the blue you decide that your base URL is `https://www.google.co.jp/`. In this case all your relative links will go to Google
> 
> No, this is not shippable like this.

This is what I want:

```razor
<MudMarkdown Value="![emw-banner](extra/emw.png)" BaseUrl="https://github.com/jdsmith2816/emw/blob/master/"/>
```

And the Markdown Component would create `<img src="https://github.com/jdsmith2816/emw/blob/master/extra/emw.png"/>`. I guess `BaseUrl` is a bad name so lets use `BaseUrlForImages` or `PrefixForRelativeLinks` or whatever.

**Comment by my-nihongo** [comment]
sorry, but I will not accept it
it makes no sense as I described in my previous comment

**Comment by erri120** [comment]
I still don't really understand where the problem with this solution is. I'm switching a website from TypeScript + React to Blazor WASM (GitHub pages) and in the old version I've used [markdown-to-jsx](https://www.npmjs.com/package/markdown-to-jsx) for rendering markdown. I solved this exact issue by using [`options.createElement`](https://www.npmjs.com/package/markdown-to-jsx#optionscreateelement---custom-reactcreateelement-behavior) where you can implement a function with custom component creation. This is how it looks like:

https://github.com/wabbajack-tools/wabbajack-tools.github.io/blob/3488df904bedde8166bedd527030b3fd702666aa/src/utils/markdown.config.ts#L158-L168

**Comment by MihailsKuzmins** [comment]
Even though I don't want to have this functionality directly in the component I will provide a "loophole" for you to modify links.
In this case all the responsibility will be on your shoulders.

I will look into it tomorrow

**Comment by MihailsKuzmins** [comment]
this is all I can do for this issue:
1. you will need to inherit from the Markdown component
2. you will need to override `string? OverrideLinkInlineUrl(string? originalUrl)` and apply your logic there

```cs
public sealed class A : MudMarkdown
{
	protected override string? OverrideLinkInlineUrl(string? originalUrl)
	{
		var newUrl = "...";
		// apply your logic
		return newUrl;
	}
}
```
