### ISSUE TITLE
new feature: add option to show image alt text below image

### ISSUE THREAD

**Issue by wanglvhang** [MyNihongo/MudBlazor.Markdown#237]
currently the alt text in markdwon 
`![image description](https://shared.lvhang.site/image.png)`
is set to img alt attribute, it will be better that markdown reader can see the "image description" below the image.

**Comment by MihailsKuzmins** [comment]
Is there a markdown specification for this request? In https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images I cannot see that there is an image description below the image.
