### ISSUE TITLE
Detach code block background color from OverlayDark

### ISSUE THREAD

**Issue by kelltom** [MyNihongo/MudBlazor.Markdown#248]
Just wanted to drop a quick issue here in case anyone is maintaining.

I notice that it's not really ideal to have the code block's bg color tied to `OverlayDark`. The below examples are using the default MudBlazor theme colors.

In light mode, you'd end up with something like this, which has poor contrast:
![chrome_ZRJcHPlQVl](https://github.com/MyNihongo/MudBlazor.Markdown/assets/44652363/42116f6a-414c-45cf-bdde-48998516ba7f)

Although it looks quite good in dark mode:
![chrome_1M1ShfceI6](https://github.com/MyNihongo/MudBlazor.Markdown/assets/44652363/2df730be-656e-44ea-8b29-362341d98a87)

We can lighten the `OverlayDark` in the MudBlazor Theme config, but this changes the appearance of all of our dialog backgrounds to appear washed out, as opposed to making a shadowy appearance.

Is there some better way to isolate the color of the code bg in light mode?

**Comment by MihailsKuzmins** [comment]
https://mudblazor.com/customization/default-theme#palette provides all available colours and back in the day `OverlayDark` seemed like the best option (even though it was not great in the light theme). Maybe there is something better now, but trying all options will take some time. Maybe `OverlayLight` would be better, but `rgba(255,255,255,0.4980392156862745)` seems like super white

**Comment by kelltom** [comment]
I found a pretty decent compromise in setting:
```csharp
OverlayDark = new MudColor(100, 100, 100, 0.3).ToString(),
```
This way, there's still a noticable tint when pulling up `MudDialogs`, and markdown looks good.

MudDialog example:
![chrome_Z5zoBhkhRq](https://github.com/MyNihongo/MudBlazor.Markdown/assets/44652363/87878601-9611-4465-b1ec-cfa3fca89c5a)

Highlight example:
![chrome_uyqGIAyjmo](https://github.com/MyNihongo/MudBlazor.Markdown/assets/44652363/1065a69d-8907-45f5-96de-1a47e152aa18)

**Comment by MihailsKuzmins** [comment]
I think that `--mud-palette-chip-default` is a pretty good option from the default library:

## Light
![image](https://github.com/MyNihongo/MudBlazor.Markdown/assets/47413092/ae4f8658-8754-43ff-82ab-3393d8e57b8e)

## Dark
![image](https://github.com/MyNihongo/MudBlazor.Markdown/assets/47413092/540cf2cc-588f-4846-859f-f73ec1f426ef)
