### ISSUE TITLE
Enable underline for links?

### ISSUE THREAD

**Issue by Stone-Red-Code** [MyNihongo/MudBlazor.Markdown#257]
Is there an option to enable the underline for links?

**Comment by MihailsKuzmins** [comment]
Just to be sure, do you want this parameter to be configurable? ↓

![image](https://github.com/MyNihongo/MudBlazor.Markdown/assets/47413092/c36406b5-5666-460f-9300-396d1a36fa13)
\* Source: https://mudblazor.com/components/link#onclick

By default a link will be underlined when one hover a cursor over it.

**Comment by Stone-Red-Code** [comment]
Yes exactly

**Comment by MihailsKuzmins** [comment]
After #258 is merged it will be possible to configure the styling of the link component as it is mentioned in this comment: https://github.com/MyNihongo/MudBlazor.Markdown/pull/258#issuecomment-2141266344
