### ISSUE TITLE
`mud-chip-palette-default` deprecated in MudBlazor v7.0

### ISSUE THREAD

**Issue by kelltom** [MyNihongo/MudBlazor.Markdown#262]
I was checking the compatibility of MudMarkdown `v1.0.1` with MudBlazor `v7.0` and noticed the code highlighting wasn't working.

After some digging, I stumbled upon this issue, which indicates `mud-chip-palette-default` is actually removed from `v7.0`: https://github.com/MudBlazor/MudBlazor/pull/8599/files

According to that PR, it was replaced with `mud-palette-action-disabled-background`.

Light Mode:
![chrome_AmGuCyjwjQ](https://github.com/MyNihongo/MudBlazor.Markdown/assets/44652363/14e0cd0b-15fe-4f1d-bb79-94acfc305f0b)

Dark Mode:
![chrome_GZhTWCrGIM](https://github.com/MyNihongo/MudBlazor.Markdown/assets/44652363/2f85d21b-0d2a-4f86-addb-9c0149321538)

**Comment by MihailsKuzmins** [comment]
Thanks!
