### ISSUE TITLE
Sample projects can't find css files

### ISSUE THREAD

**Issue by Stone-Red-Code** [MyNihongo/MudBlazor.Markdown#271]
Edit:
Seems like this is only an issue in the sample projects because it can't find the `_content/MudBlazor.Markdown/MudBlazor.Markdown.min.css` file for some reason.

Original:
Unordered lists don't have a style and incorrect indentation:

![image](https://github.com/user-attachments/assets/d4536412-f134-42bc-8a6a-8f3e2392a1a9)

The numbers of ordered lists are shifted to the left and the indentation is also wrong here.
![image](https://github.com/user-attachments/assets/aea91152-c60b-4f72-b306-6bcf205b1f56)

**Comment by MihailsKuzmins** [comment]
With the develop branch I have run the sample project and there are no issues. The content is displayed correctly and all CSS files are loaded

![image](https://github.com/user-attachments/assets/4f3dee84-ae04-40f7-906a-f2621aa3a7d3)

![image](https://github.com/user-attachments/assets/a20f64ba-f57e-4cea-99ab-fdb9714568b9)

**Comment by my-nihongo** [comment]
Please see the readme file at https://github.com/MyNihongo/MudBlazor.Markdown/tree/main/samples
Sorry for not providing enough detail about how to debug the solution

![image](https://github.com/user-attachments/assets/26eae60f-7462-481b-be05-2607fe346fc0)
