### ISSUE TITLE
Content after Code block is not rendered

### ISSUE THREAD

**Issue by gingters** [MyNihongo/MudBlazor.Markdown#64]
Hello,

I found an issue with content not rendered after a code block.
The first element that happens to be after a code block will not be displayed with MudBlazor.Markdown. When inspecting the rendered HTML with Devtools the element is really not rendered to the website.

I use Blazor WASM 6.0.1, MudBlazor 6.0.5 and MudBlazor.Markdown 0.0.6.
I also first tried to repro this issue with Markdig 0.26.0 standalone to make sure it isn't a Markdig issue, but Markdig alone renders the samples correctly, so it seems to come from MudBlazor.Markdown itself.

Repro:

Given the following Markdown content:

````markdown
# Heading 1
Some text.

```csharp
public int GetTheAnswer()
{
   return 42;
}
```

## Another headline <-- this element is NOT rendered with MudBlazor.Markdown
## Another headline <-- this element is shown again
````

It really doesn't matter what follows the code block. The whole next element will be ignored. In the following example the whole list with all three items is not rendered to the page and ignored:

````markdown
```text
some
code
```

* List item 1
* List item 2
* List item 3

## Another headline <-- this element is shown again
````

**Comment by my-nihongo** [comment]
@gingters thank you for reporting the issue
@MihailsKuzmins, please investigate

**Comment by MihailsKuzmins** [comment]
damn, stupid iteration mistake with `_i` and `i` 😄 
renamed the variables in order not to make the same mistakes (and unit tests of course)

@my-nihongo please review the pr

**Comment by my-nihongo** [comment]
@gingters, a new NeGet package v0.0.7 has been published. It should be available within a few minutes.  
Please reopen the issue if the problem still persists
