### ISSUE TITLE
Static resources missing in version 0.0.7

### ISSUE THREAD

**Issue by adeotek** [MyNihongo/MudBlazor.Markdown#66]
I've tryed using the latest version (0.0.7) and it seems that the static resources (CSS and JS) are missing from the NuGet package. From what I've seen, they are present in the project, but missing from package.

**Comment by MihailsKuzmins** [comment]
this is super weird. Probably related to .net6 https://github.com/dotnet/aspnetcore/issues/35345 or https://github.com/dotnet/aspnetcore/issues/36740.  
With the current `csproj` structure one build produces `staticwebassets`, but the next build doesn't...

**Comment by MihailsKuzmins** [comment]
I have manually pushed https://www.nuget.org/packages/MudBlazor.Markdown/0.0.8  
It contains all static files, so it should solve this issue I hope  
![image](https://user-images.githubusercontent.com/47413092/150693912-3289eae8-53cc-41e6-b6f5-ef8be7a2e1d1.png)

**Comment by adeotek** [comment]
Now it works as expected. Thank you.
