### ISSUE TITLE
Broken Link in README in Palette Section

### ISSUE THREAD

**Issue by alvaromon** [MyNihongo/MudBlazor.Markdown#87]
There is a broken link in the README in regards to how to use the pallette. I am having trouble with code blocks but im positive im doing something wrong but im just trying to learn

my project: https://github.com/alvaromon/BitbyBitBlog.git Sprint1 branch

Im running into an issue that my site Theme is overwriting the text color for fenced code blocks

example using `CodeBlockTheme.DarkVioletBase16` where text is supposed to be light pink.
![image](https://user-images.githubusercontent.com/7915170/164336811-66f84585-7d01-471e-aef6-0c9585d17dbb.png)
![image](https://user-images.githubusercontent.com/7915170/164336902-b4f803d7-cb0f-4c82-8aac-410618baaf98.png)

**Comment by MihailsKuzmins** [comment]
Thanks for submitting the issue.
The fact is that these styles were not meant for `hljs` in the first place - I have fixed it. I have updated the broken link as well.

Unfortunately, I have checked all pages in your repo (branch Sprint1) and haven't found a page where MudMarkdown is used, so I was not able to test the solution with your page, sorry :(

Nevertheless, I have removed styling from `hljs`, so I think that it should solve your issue. I have released a new [NuGet 0.0.10](https://www.nuget.org/packages/MudBlazor.Markdown/0.0.10) - could you please test whether it works now or not?
